### ISSUE TITLE
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by suprola1017** [SMARTlab-Purdue/Husformer#1]
when I run the main.py
______________________________________________________________________________________________________________________________________________
Start loading the data....
Husformer-master\data\husformer_train.dt
  - Found cached train data
Husformer-master\data\husformer_valid.dt
  - Found cached valid data
Husformer-master\data\husformer_test.dt
  - Found cached test data
Finish loading the data....
Traceback (most recent call last):
  File "c:/Colleage/EEG论文/其他课程论文/Husformer A Multi-Modal Transformer for Multi-Modal Human State Recognition/Husformer-master/Husformer-master/main.py", line 121, in <module>
    test_loss = train.initiate(hyp_params, train_loader, valid_loader, test_loader)
  File "c:\Colleage\EEG论文\其他课程论文\Husformer A Multi-Modal Transformer for Multi-Modal Human State Recognition\Husformer-master\Husformer-master\src\train.py", line 32, in initiate
    return train_model(settings, hyp_params, train_loader, valid_loader, test_loader)
  File "c:\Colleage\EEG论文\其他课程论文\Husformer A Multi-Modal Transformer for Multi-Modal Human State Recognition\Husformer-master\Husformer-master\src\train.py", line 139, in train_model
    _,mae_train = train(model, optimizer, criterion)
  File "c:\Colleage\EEG论文\其他课程论文\Husformer A Multi-Modal Transformer for Multi-Modal Human State Recognition\Husformer-master\Husformer-master\src\train.py", line 47, in train
    for i_batch, (batch_X, batch_Y, batch_META) in enumerate(train_loader):
  File "C:\Software\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Software\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "C:\Software\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "C:\Software\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "C:\Software\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 132, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

**Comment by suprola1017** [comment]
Fixed, the pytorch version is incorrect
