### ISSUE TITLE
Unable to run the main.py for Cogload dataset

### ISSUE THREAD

**Issue by shahaamirbader** [SMARTlab-Purdue/Husformer#7]
Hi,

First of all thank you for sharing such awesome work with us. I have few questions, since I am unable to run the main.py

1. Given that you have already provided cogload.pkl file, do we still need to download the cogload the dataset and rename each of its .csv files into .pkl and follow the make data process as you have mentioned?
2. There is no .py file in the make_data folder for converting the cogload dataset into modalities. Can you explain how the modalities are created for cogload dataset. If I simply rename the provided file cogload.pkl to husfromer.pkl I get the following error:
```
❯ python main.py 
Start loading the data....
  - Creating new train data
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    train_data = get_data(args, dataset, 'train')
  File "/data/4th_Year/Husformer/src/utils.py", line 12, in get_data
    data = Multimodal_Datasets(args.data_path, dataset, split)
  File "/data/4th_Year/Husformer/src/dataset.py", line 20, in __init__
    self.m1 = torch.tensor(dataset[split_type]['modality_1'].astype(np.float32)).cpu().detach()
KeyError: 'modality_1'
```

If I look into the cogload.pkl file and read the contents, I only get the following and no modalities 

```
\dict_keys(['train', 'valid', 'test'])
dict_keys(['id', 'eeg', 'gsr', 'bvp', 'label', 'pow'])
```

3. As an example it would be helpful if you could share what the file structure should look like for a working code. Since the instructions are vague with respect to placing files in src folder.

**Comment by Xavier-Y-Yu** [comment]
Have you solved this "KeyError: 'modality_1'" problem? I troubled with this problem too.
